'use strict';
var a11yModule = angular.module('a11yModule', ['ui.bootstrap']);
a11yModule.factory('a11yCommon', ['$q', '$timeout', function ($q, $timeout) {
    return {
        getKeyCodes: function () {
            return {
                "backspace": 8,
                "tab": 9,
                "enter": 13,
                "shift": 16,
                "ctrl": 17,
                "alt": 18,
                "esc": 27,
                "space": 32,
                "pageup": 33,
                "pagedown": 34,
                "end": 35,
                "home": 36,
                "left": 37,
                "up": 38,
                "right": 39,
                "down": 40,
                "del": 46,
            };
        },

        getFilteredStates: function (searchString) {
            var testPattern = new RegExp('^' + searchString, 'i');
            var filteredUSStates = this.USStates.filter(function (item) {
                return testPattern.test(item.name);
            });
            return filteredUSStates;
        },

        getFilteredCities: function (searchString) {
            var testPattern = new RegExp('^' + searchString, 'i');
            var filteredUSCities = this.USCities.filter(function (item) {
                return testPattern.test(item);
            });
            return filteredUSCities;
        },

        getFilteredCountries: function (searchString) {
            var testPattern = new RegExp( searchString, 'i');
            var filteredAsianCountries = this.AsianCountries.filter(function (item) {
                return testPattern.test(item.name);
            });
            return filteredAsianCountries;
        },

        USStates: [
            { "code": "AL", "name": "Alabama" },
            { "code": "AK", "name": "Alaska" },
            { "code": "AS", "name": "American Samoa" },
            { "code": "AZ", "name": "Arizona" },
            { "code": "AR", "name": "Arkansas" },
            { "code": "CA", "name": "California" },
            { "code": "CO", "name": "Colorado" },
            { "code": "CT", "name": "Connecticut" },
            { "code": "DE", "name": "Delaware" },
            { "code": "DC", "name": "District of Columbia" },
            { "code": "FL", "name": "Florida" },
            { "code": "GA", "name": "Georgia" },
            { "code": "GU", "name": "Guam" },
            { "code": "HI", "name": "Hawaii" },
            { "code": "ID", "name": "Idaho" },
            { "code": "IL", "name": "Illinois" },
            { "code": "IN", "name": "Indiana" },
            { "code": "IA", "name": "Iowa" },
            { "code": "KS", "name": "Kansas" },
            { "code": "KY", "name": "Kentucky" },
            { "code": "LA", "name": "Louisiana" },
            { "code": "ME", "name": "Maine" },
            { "code": "MD", "name": "Maryland" },
            { "code": "MA", "name": "Massachusetts" },
            { "code": "MI", "name": "Michigan" },
            { "code": "MN", "name": "Minnesota" },
            { "code": "MS", "name": "Mississippi" },
            { "code": "MO", "name": "Missouri" },
            { "code": "MT", "name": "Montana" },
            { "code": "NE", "name": "Nebraska" },
            { "code": "NV", "name": "Nevada" },
            { "code": "NH", "name": "New Hampshire" },
            { "code": "NJ", "name": "New Jersey" },
            { "code": "NM", "name": "New Mexico" },
            { "code": "NY", "name": "New York" },
            { "code": "NC", "name": "North Carolina" },
            { "code": "ND", "name": "North Dakota" },
            { "code": "MP", "name": "Northern Marianas Islands" },
            { "code": "OH", "name": "Ohio" },
            { "code": "OK", "name": "Oklahoma" },
            { "code": "OR", "name": "Oregon" },
            { "code": "PA", "name": "Pennsylvania" },
            { "code": "PR", "name": "Puerto Rico" },
            { "code": "RI", "name": "Rhode Island" },
            { "code": "SC", "name": "South Carolina" },
            { "code": "SD", "name": "South Dakota" },
            { "code": "TN", "name": "Tennessee" },
            { "code": "TX", "name": "Texas" },
            { "code": "UT", "name": "Utah" },
            { "code": "VT", "name": "Vermont" },
            { "code": "VA", "name": "Virginia" },
            { "code": "VI", "name": "Virgin Islands" },
            { "code": "WA", "name": "Washington" },
            { "code": "WV", "name": "West Virginia" },
            { "code": "WI", "name": "Wisconsin" },
            { "code": "WY", "name": "Wyoming" },
        ],

        USCities: ['Abilene',
            'Akron',
            'Albuquerque',
            'Alexandria',
            'Allentown',
            'Amarillo',
            'Anaheim',
            'Anchorage',
            'Ann Arbor',
            'Antioch',
            'Arlington',
            'Arvada',
            'Athens',
            'Atlanta',
            'Augusta',
            'Aurora',
            'Austin',
            'Bakersfield',
            'Baltimore',
            'Baton Rouge',
            'Beaumont',
            'Bellevue',
            'Berkeley',
            'Billings',
            'Birmingham',
            'Boise',
            'Boston',
            'Boulder',
            'Bridgeport',
            'Broken Arrow',
            'Brownsville',
            'Buffalo',
            'Burbank',
            'Cambridge',
            'Cape Coral',
            'Carlsbad',
            'Carrollton',
            'Cary',
            'Cedar Rapids',
            'Centennial',
            'Chandler',
            'Charleston',
            'Charlotte',
            'Chattanooga',
            'Chesapeake',
            'Chicago',
            'Chula Vista',
            'Cincinnati',
            'Clarksville',
            'Clearwater',
            'Cleveland',
            'Clovis',
            'College Station',
            'Colorado Springs',
            'Columbia',
            'Columbus',
            'Concord',
            'Coral Springs',
            'Corona',
            'Corpus Christi',
            'Costa Mesa',
            'Dallas',
            'Daly City',
            'Davenport',
            'Davie',
            'Dayton',
            'Denton',
            'Denver',
            'Des Moines',
            'Detroit',
            'Downey',
            'Durham',
            'Edison',
            'El Cajon',
            'El Monte',
            'El Paso',
            'Elgin',
            'Elizabeth',
            'Elk Grove',
            'Escondido',
            'Eugene',
            'Evansville',
            'Everett',
            'Fairfield',
            'Fargo',
            'Fayetteville',
            'Fontana',
            'Fort Collins',
            'Fort Lauderdale',
            'Fort Wayne',
            'Fort Worth',
            'Fremont',
            'Fresno',
            'Frisco',
            'Fullerton',
            'Gainesville',
            'Garden Grove',
            'Garland',
            'Gilbert',
            'Glendale',
            'Grand Prairie',
            'Grand Rapids',
            'Greeley',
            'Green Bay',
            'Greensboro',
            'Gresham',
            'Hampton',
            'Hartford',
            'Hayward',
            'Henderson',
            'Hialeah',
            'High Point',
            'Hillsboro',
            'Hollywood',
            'Honolulu',
            'Houston',
            'Huntington Beach',
            'Huntsville',
            'Independence',
            'Indianapolis',
            'Inglewood',
            'Irvine',
            'Irving',
            'Jackson',
            'Jacksonville',
            'Jersey City',
            'Joliet',
            'Jurupa Valley',
            'Kansas City',
            'Kent',
            'Killeen',
            'Knoxville',
            'Lafayette',
            'Lakeland',
            'Lakewood',
            'Lancaster',
            'Lansing',
            'Laredo',
            'Las Cruces',
            'Las Vegas',
            'Lewisville',
            'Lexington',
            'Lincoln',
            'Little Rock',
            'Long Beach',
            'Los Angeles',
            'Louisville',
            'Lowell',
            'Lubbock',
            'Macon',
            'Madison',
            'Manchester',
            'McAllen',
            'McKinney',
            'Memphis',
            'Mesa',
            'Mesquite',
            'Miami',
            'Miami Gardens',
            'Midland',
            'Milwaukee',
            'Minneapolis',
            'Miramar',
            'Mobile',
            'Modesto',
            'Montgomery',
            'Moreno Valley',
            'Murfreesboro',
            'Murrieta',
            'Naperville',
            'Nashville',
            'New Haven',
            'New Orleans',
            'New York',
            'Newark',
            'Newport',
            'Norfolk',
            'Norman',
            'North Charleston',
            'North Las Vegas',
            'Norwalk',
            'Oakland',
            'Oceanside',
            'Odessa',
            'Oklahoma City',
            'Olathe',
            'Omaha',
            'Ontario',
            'Orange',
            'Orlando',
            'Overland Park',
            'Oxnard',
            'Palm Bay',
            'Palmdale',
            'Pasadena',
            'Paterson',
            'Pearland',
            'Pembroke Pines',
            'Peoria',
            'Philadelphia',
            'Phoenix',
            'Pittsburgh',
            'Plano',
            'Pomona',
            'Pompano Beach',
            'Port St. Lucie',
            'Portland',
            'Providence',
            'Provo',
            'Pueblo',
            'Raleigh',
            'Rancho Cucamonga',
            'Reno',
            'Renton',
            'Rialto',
            'Richardson',
            'Richmond',
            'Riverside',
            'Rochester',
            'Rockford',
            'Roseville',
            'Round Rock',
            'Sacramento',
            'Saint Paul',
            'Salem',
            'Salinas',
            'Salt Lake City',
            'San Angelo',
            'San Antonio',
            'San Bernardino',
            'San Diego',
            'San Francisco',
            'San Jose',
            'San Mateo',
            'Sandy Springs',
            'Santa Ana',
            'Santa Clara',
            'Santa Clarita',
            'Santa Maria',
            'Santa Rosa',
            'Savannah',
            'Scottsdale',
            'Seattle',
            'Shreveport',
            'Simi Valley',
            'Sioux Falls',
            'South Bend',
            'Spokane',
            'Springfield',
            'St. Louis',
            'St. Petersburg',
            'Stamford',
            'Sterling Heights',
            'Stockton',
            'Sunnyvale',
            'Surprise',
            'Syracuse',
            'Tacoma',
            'Tallahassee',
            'Tampa',
            'Temecula',
            'Tempe',
            'Thornton',
            'Thousand Oaks',
            'Toledo',
            'Topeka',
            'Torrance',
            'Tucson',
            'Tulsa',
            'Tyler',
            'Vallejo',
            'Vancouver',
            'Ventura',
            'Victorville',
            'Virginia Beach',
            'Visalia',
            'Vista',
            'Waco',
            'Warren',
            'Washington',
            'Waterbury',
            'West Covina',
            'West Jordan',
            'West Palm Beach',
            'West Valley City',
            'Westminster',
            'Wichita',
            'Wichita Falls',
            'Wilmington',
            'Winston',
            'Woodbridge',
            'Worcester',
            'Yonkers'
        ],

        AsianCountries: [
            { "code": "AF", "name": "Afghanistan" },
            { "code": "AR", "name": "Armenia" },
            { "code": "AZ", "name": "Azerbaijan" },
            { "code": "BA", "name": "Bahrain" },
            { "code": "BN", "name": "Bangladesh" },
            { "code": "BH", "name": "Bhutan" },
            { "code": "BR", "name": "Brunei" },
            { "code": "CA", "name": "Cambodia" },
            { "code": "CH", "name": "China" },
            { "code": "CY", "name": "Cyprus" },
            { "code": "GE", "name": "Georgia" },
            { "code": "IN", "name": "India" },
            { "code": "ID", "name": "Indonesia" },
            { "code": "IR", "name": "Iran" },
            { "code": "IA", "name": "Iraq" },
            { "code": "IS", "name": "Israel" },
            { "code": "JA", "name": "Japan" },
            { "code": "JO", "name": "Jordan" },
            { "code": "KA", "name": "Kazakhstan" },
            { "code": "KU", "name": "Kuwait" },
            { "code": "KY", "name": "Kyrgyzstan" },
            { "code": "LA", "name": "Laos" },
            { "code": "LE", "name": "Lebanon" },
            { "code": "MA", "name": "Malaysia" },
            { "code": "ML", "name": "Maldives" },
            { "code": "MO", "name": "Mongolia" },
            { "code": "MY", "name": "Myanmar (Burma)" },
            { "code": "NE", "name": "Nepal" },
            { "code": "NO", "name": "North Korea" },
            { "code": "OM", "name": "Oman" },
            { "code": "PA", "name": "Pakistan" },
            { "code": "PL", "name": "Palestine" },
            { "code": "PH", "name": "Philippines" },
            { "code": "QA", "name": "Qatar" },
            { "code": "RU", "name": "Russia" },
            { "code": "SA", "name": "Saudi Arabia" },
            { "code": "SI", "name": "Singapore" },
            { "code": "SO", "name": "South Korea" },
            { "code": "SR", "name": "Sri Lanka" },
            { "code": "SY", "name": "Syria" },
            { "code": "TA", "name": "Taiwan" },
            { "code": "TJ", "name": "Tajikistan" },
            { "code": "TH", "name": "Thailand" },
            { "code": "TI", "name": "Timor-Leste" },
            { "code": "TU", "name": "Turkey" },
            { "code": "TK", "name": "Turkmenistan" },
            { "code": "UA", "name": "United Arab Emirates" },
            { "code": "UZ", "name": "Uzbekistan" },
            { "code": "VI", "name": "Vietnam" },
            { "code": "YE", "name": "Yemen" }
        ]
    };
}])